### PR TITLE
remove the recommendation to include a source.type attribute

### PR DESCRIPTION
**Pull request by jkwatson**

### CODE REVIEW

**Comment by a-feld** [comment]
`source.type` is also referenced in the [opencensus](https://github.com/newrelic/newrelic-exporter-specs/blame/master/opencensus/OpenCensus-Metrics.md#L27) guidelines

**Comment by jkwatson** [comment]
I wanted to keep the guidelines separate from the actual implementations. Should I remove things from opencensus as a part of this PR?

**Comment by a-feld** [comment]
I'm not sure, it's also in dropwizard so if we remove it in opencensus I would also remove it in dropwizard. I think it makes sense if we're actually removing this attribute from implementations we should probably remove it in all places.

**Comment by jkwatson** [comment]
since I wanted the actual specs for the individual exporters to reflect current reality (not aspirational reality), I'm saving the dropwizard/micrometer updates until the latest published version of those libraries has it removed.

**Pull request merged**
