### PR TITLE
Create errors.md

### PR DESCRIPTION
**Pull request by jeffalder**

### CODE REVIEW

**Comment by jkwatson** [comment]
It seems like this should be linked to from the main LiC spec. Otherwise, it'll be hidden pretty well in a directory structure.

**Comment by justinfoote** [comment]
Agreed.  Or it should just be included in the main `logging/readme.md`.

**Comment by jeffalder** [comment]
@justinfoote @jkwatson OK, I moved the fields to logging/README.md

**Comment by jkwatson** [comment]
My last question: is this a prescriptive or descriptive entry in the specs? We should definitely call that out to reduce possible confusing.

**Comment by jeffalder** [comment]
@jkwatson The only real prescriptive entries are `message`, `timestamp`, and the linking metadata. All the rest are descriptive. Suggestions?

**Comment by jkwatson** [comment]
@jeffalder probably just call that out explicitly in the rationale, in a note of some sort. No harm in being super clear about the state of the implementations.

**Comment by justinfoote** [comment]
The main headings of this page are:
```markdown
### Required fields

### Common Optional Fields

### Errors
```

Perhaps the solution is just to nest `Errors` beneath `Common Optional Fields`?

**Comment by jeffalder** [comment]
@justinfoote @jkwatson Streamlined the text and moved it under optional fields

**Pull request merged**
